version: '3'

services:
  flask:
    build: ./src
    environment:
      - FLASK_APP_CONFIG=config.ProductionConfig
      - VIRTUAL_HOST=filmogram.net,www.filmogram.net
      - VIRTUAL_PORT=5000
      - LETSENCRYPT_HOST=filmogram.net,www.filmogram.net
      - LETSENCRYPT_EMAIL=michael.sergio.barnes@gmail.com
    depends_on:
      - db

  db:
    image: postgres:9.6.5
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
