version: '3'

services:
  web:
    build: ./src
    volumes:
      - static:/app/app/static/
    networks:
      - filmogram_web_nw
      - filmogram_db_nw
    environment:
      FLASK_APP_CONFIG: "config.ProductionConfig"
    depends_on:
      - db

  db:
    image: postgres:9.6.5
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - filmogram_db_nw

  nginx:
    build: ./src/nginx
    volumes:
      - static:/app/app/static/
    networks:
      - filmogram_web_nw
    depends_on:
      - web

networks:
  filmogram_db_nw:
    driver: bridge
  filmogram_web_nw:
    driver: bridge

volumes:
   db:
   static:
