"""Add data to notifications

Revision ID: 35d31d1edb72
Revises: 7bb0c2315c9c
Create Date: 2018-02-03 20:14:44.351401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35d31d1edb72'
down_revision = '7bb0c2315c9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('payload_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'payload_json')
    # ### end Alembic commands ###
