"""Add body to user_notifications

Revision ID: 90e926b50912
Revises: 26c94a6d068a
Create Date: 2018-02-04 22:55:56.716161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90e926b50912'
down_revision = '26c94a6d068a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_notification', sa.Column('body', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_notification', 'body')
    # ### end Alembic commands ###
