"""remove photo filename

Revision ID: d53604ac0557
Revises: 81d71f97c789
Create Date: 2018-05-02 05:07:27.236853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd53604ac0557'
down_revision = '81d71f97c789'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'photo_filename')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('photo_filename', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
