version: '3'

services:
  web:
    build: .
    volumes:
      - static:/app/app/static/
    networks:
      - filmogram_web_nw
      - filmogram_db_nw
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URI: "postgresql://postgres:P@ssw0rd!@db/postgres"

  db:
    image: postgres:9.6.5
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - filmogram_db_nw
    environment:
      POSTGRES_PASSWORD: "P@ssw0rd!"

  nginx:
    build: ./nginx
    ports:
      - "5000:80"
    volumes:
      - static:/app/app/static/
    networks:
      - filmogram_web_nw
    depends_on:
      - web

networks:
  filmogram_db_nw:
    driver: bridge
  filmogram_web_nw:
    driver: bridge

volumes:
   db:
   static:
