"""AddProfileImgColumn

Revision ID: debc548b0561
Revises: a96e8bc0f8cb
Create Date: 2018-02-01 23:00:13.362260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'debc548b0561'
down_revision = 'a96e8bc0f8cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_img_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_img_url')
    # ### end Alembic commands ###
