version: '3'

services:
  web:
    build: .
    ports:
      - "8000:5000"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "P@ssw0rd!"
      POSTGRES_Db: "filmogram"
